// SPDX-License-Identifier: MIT OR Apache-2.0

//! Wire-compatibility tests against real `.nir` files written by the Python
//! reference implementation.
//!
//! These are the evidence that the reader is wire-accurate rather than merely
//! self-consistent: every file in `tests/fixtures/` was produced by h5py via
//! upstream `nir.write`, and none of it was generated by this crate. See
//! `tests/fixtures/README.md` for provenance and license.

#![cfg(feature = "hdf5")]

use nir_rs::nodes::Padding;
use nir_rs::types::{DType, TensorData};
use nir_rs::{NirGraph, NirNode};

fn read(name: &str) -> NirGraph {
    nir_rs::io::read(format!("tests/fixtures/{name}"))
        .unwrap_or_else(|e| panic!("reading {name}: {e}"))
}

fn type_names(graph: &NirGraph) -> Vec<(&str, &'static str)> {
    graph
        .nodes
        .iter()
        .map(|(name, node)| (name.as_str(), node.type_name()))
        .collect()
}

fn f32s(data: &TensorData) -> &[f32] {
    match data {
        TensorData::F32(v) => v,
        other => panic!("expected f32 data, found {:?}", other.dtype()),
    }
}

fn f64s(data: &TensorData) -> &[f64] {
    match data {
        TensorData::F64(v) => v,
        other => panic!("expected f64 data, found {:?}", other.dtype()),
    }
}

fn i64s(data: &TensorData) -> &[i64] {
    match data {
        TensorData::I64(v) => v,
        other => panic!("expected i64 data, found {:?}", other.dtype()),
    }
}

// ---------------------------------------------------------------------------
// lif_norse.nir — the minimal graph, f32, with `v_reset` absent on the wire
// ---------------------------------------------------------------------------

#[test]
fn lif_norse_structure_and_values() {
    let g = read("lif_norse.nir");

    assert_eq!(g.version.as_deref(), Some("0.1.1"));
    assert_eq!(
        type_names(&g),
        [
            ("0", "Affine"),
            ("1", "LIF"),
            ("input", "Input"),
            ("output", "Output"),
        ]
    );
    assert_eq!(
        g.edges,
        [
            ("input".to_owned(), "0".to_owned()),
            ("0".to_owned(), "1".to_owned()),
            ("1".to_owned(), "output".to_owned()),
        ]
    );
    g.validate_structure().unwrap();

    let NirNode::Input(input) = g.get("input").unwrap() else {
        panic!("expected Input");
    };
    assert_eq!(input.shape, [1]);

    let NirNode::Affine(affine) = g.get("0").unwrap() else {
        panic!("expected Affine");
    };
    assert_eq!(affine.weight.shape(), [1, 1]);
    assert_eq!(f32s(affine.weight.data()), [1.0]);
    assert_eq!(f32s(affine.bias.data()), [0.0]);

    let NirNode::Lif(lif) = g.get("1").unwrap() else {
        panic!("expected LIF");
    };
    assert_eq!(lif.tau.dtype(), DType::F32, "f32 must not widen to f64");
    assert_eq!(f32s(lif.tau.data()), [0.0025]);
    assert_eq!(f32s(lif.r.data()), [1.0]);
    assert_eq!(f32s(lif.v_leak.data()), [0.0]);
    assert_eq!(f32s(lif.v_threshold.data()), [0.1]);
}

#[test]
fn absent_v_reset_defaults_to_zeros_like_threshold() {
    let g = read("lif_norse.nir");
    let NirNode::Lif(lif) = g.get("1").unwrap() else {
        panic!("expected LIF");
    };

    // The dataset is genuinely absent in the file, so this value can only come
    // from the Python-compatible default.
    let v_reset = lif.v_reset.as_ref().expect("v_reset should be defaulted");
    assert_eq!(v_reset.shape(), lif.v_threshold.shape());
    assert_eq!(v_reset.dtype(), lif.v_threshold.dtype());
    assert_eq!(f32s(v_reset.data()), [0.0]);
}

#[test]
fn read_version_matches_graph_version() {
    let version = nir_rs::io::read_version("tests/fixtures/lif_norse.nir").unwrap();
    assert_eq!(version, "0.1.1");
    assert_eq!(read("lif_norse.nir").version, Some(version));
}

// ---------------------------------------------------------------------------
// two_lif_neurons.nir — f64 throughout
// ---------------------------------------------------------------------------

#[test]
fn two_lif_neurons_preserves_f64() {
    let g = read("two_lif_neurons.nir");

    assert_eq!(
        type_names(&g),
        [
            ("in", "Input"),
            ("lif1", "LIF"),
            ("lif2", "LIF"),
            ("linear1", "Linear"),
            ("linear2", "Linear"),
            ("out", "Output"),
        ]
    );
    assert_eq!(g.edges.len(), 5);
    assert_eq!(g.edges[0], ("in".to_owned(), "linear1".to_owned()));
    g.validate_structure().unwrap();

    let NirNode::Linear(linear) = g.get("linear1").unwrap() else {
        panic!("expected Linear");
    };
    assert_eq!(linear.weight.dtype(), DType::F64, "f64 must not narrow");
    assert_eq!(linear.weight.shape(), [1, 1]);
    assert_eq!(f64s(linear.weight.data()), [1.0]);

    let NirNode::Lif(lif) = g.get("lif1").unwrap() else {
        panic!("expected LIF");
    };
    assert_eq!(f64s(lif.tau.data()), [0.01]);
    assert_eq!(f64s(lif.v_leak.data()), [1.2]);
    assert_eq!(f64s(lif.v_threshold.data()), [1.0]);
}

// ---------------------------------------------------------------------------
// braille_noDelay_bias_zero.nir — CubaLIF, recurrence, dotted node names
// ---------------------------------------------------------------------------

#[test]
fn braille_has_recurrence_and_dotted_node_names() {
    let g = read("braille_noDelay_bias_zero.nir");

    assert_eq!(
        type_names(&g),
        [
            ("fc1", "Affine"),
            ("fc2", "Affine"),
            ("input", "Input"),
            ("lif1.lif", "CubaLIF"),
            ("lif1.w_rec", "Affine"),
            ("lif2", "CubaLIF"),
            ("output", "Output"),
        ],
        "dotted names are flat keys, not nested paths"
    );

    // The recurrent pair: lif1.lif -> lif1.w_rec -> lif1.lif.
    assert!(
        g.edges
            .contains(&("lif1.lif".to_owned(), "lif1.w_rec".to_owned()))
    );
    assert!(
        g.edges
            .contains(&("lif1.w_rec".to_owned(), "lif1.lif".to_owned()))
    );
    // Cycles are legal, so the graph still validates.
    g.validate_structure().unwrap();

    let NirNode::CubaLif(cuba) = g.get("lif1.lif").unwrap() else {
        panic!("expected CubaLIF");
    };
    assert_eq!(cuba.tau_syn.shape(), [38]);
    assert_eq!(cuba.tau_syn.dtype(), DType::F64);
    assert_eq!(f64s(cuba.tau_mem.data())[0], 0.0009999997615814777);
    assert_eq!(f64s(cuba.r.data())[0], 9.999997615814776);
    // w_in is present in this file, so it is read rather than defaulted.
    let w_in = cuba.w_in.as_ref().expect("w_in present in this fixture");
    assert_eq!(f64s(w_in.data())[0], 2.2222222810910086);
    // v_reset is absent, so it is defaulted.
    let v_reset = cuba.v_reset.as_ref().unwrap();
    assert_eq!(f64s(v_reset.data()), vec![0.0; 38]);
}

// ---------------------------------------------------------------------------
// braille_..._subgraph.nir — nested NIRGraph on the wire
// ---------------------------------------------------------------------------

#[test]
fn nested_nirgraph_becomes_a_boxed_subgraph() {
    let g = read("braille_noDelay_bias_zero_subgraph.nir");

    assert_eq!(g.get("lif1").unwrap().type_name(), "NIRGraph");
    let NirNode::Graph(sub) = g.get("lif1").unwrap() else {
        panic!("expected a nested graph");
    };

    assert_eq!(
        type_names(sub),
        [
            ("input", "Input"),
            ("lif1", "CubaLIF"),
            ("lin", "Affine"),
            ("output", "Output"),
        ]
    );
    assert_eq!(sub.edges.len(), 4);
    assert_eq!(sub.version, None, "only the root graph carries /version");

    let NirNode::CubaLif(cuba) = sub.get("lif1").unwrap() else {
        panic!("expected CubaLIF inside the subgraph");
    };
    assert_eq!(cuba.tau_syn.shape(), [38]);
}

#[test]
fn upstream_subgraph_fixture_has_an_unresolved_inner_edge() {
    // Documented upstream quirk: the inner graph's edges name a node "lif",
    // but the node is called "lif1". Python only loads this file with
    // type_check=False. `read` stays faithful to the file, and validation is
    // where the inconsistency surfaces.
    let g = read("braille_noDelay_bias_zero_subgraph.nir");
    let err = g.validate_structure().unwrap_err();
    let message = err.to_string();
    assert!(
        message.contains("lif1"),
        "should name the subgraph: {message}"
    );
    assert!(message.contains("lif"), "should name the edge: {message}");
}

// ---------------------------------------------------------------------------
// cnn_sinabs.nir — Conv2d, IF, SumPool2d, Flatten
// ---------------------------------------------------------------------------

#[test]
fn cnn_conv2d_fields() {
    let g = read("cnn_sinabs.nir");
    g.validate_structure().unwrap();

    let NirNode::Conv2d(conv) = g.get("0").unwrap() else {
        panic!("expected Conv2d");
    };
    assert_eq!(conv.weight.shape(), [16, 2, 5, 5]);
    assert_eq!(conv.weight.dtype(), DType::F32);
    assert_eq!(conv.stride, [2, 2]);
    assert_eq!(conv.dilation, [1, 1]);
    assert_eq!(conv.padding, Padding::pair(1, 1));
    assert_eq!(conv.groups, 1, "scalar integer field");
    assert_eq!(conv.bias.shape(), [16]);
    assert_eq!(conv.input_shape.as_deref(), Some([34, 34].as_slice()));
}

#[test]
fn cnn_pooling_and_flatten_fields() {
    let g = read("cnn_sinabs.nir");

    let NirNode::SumPool2d(pool) = g.get("4").unwrap() else {
        panic!("expected SumPool2d");
    };
    assert_eq!(i64s(pool.kernel_size.data()), [2, 2]);
    assert_eq!(i64s(pool.stride.data()), [2, 2]);
    assert_eq!(i64s(pool.padding.data()), [0, 0]);

    let NirNode::Flatten(flatten) = g.get("8").unwrap() else {
        panic!("expected Flatten");
    };
    assert_eq!(flatten.start_dim, 0);
    assert_eq!(flatten.end_dim, -1);
    assert_eq!(flatten.input_type.as_deref(), Some([8, 4, 4].as_slice()));

    let NirNode::If(if_node) = g.get("1").unwrap() else {
        panic!("expected IF");
    };
    assert_eq!(if_node.r.shape(), [16, 16, 16]);
    // Absent on the wire, defaulted from v_threshold.
    assert_eq!(
        if_node.v_reset.as_ref().unwrap().shape(),
        if_node.v_threshold.shape()
    );

    let NirNode::Input(input) = g.get("input").unwrap() else {
        panic!("expected Input");
    };
    assert_eq!(input.shape, [2, 34, 34], "multi-axis input shape");
}

#[test]
fn every_fixture_node_is_a_known_wire_type() {
    fn check(graph: &NirGraph) {
        for node in graph.nodes.values() {
            assert!(
                nir_rs::io::wire::is_wire_type(node.type_name()),
                "{} is not a wire type",
                node.type_name()
            );
            if let NirNode::Graph(sub) = node {
                check(sub);
            }
        }
    }

    for name in [
        "lif_norse.nir",
        "two_lif_neurons.nir",
        "braille_noDelay_bias_zero.nir",
        "braille_noDelay_bias_zero_subgraph.nir",
        "cnn_sinabs.nir",
    ] {
        check(&read(name));
    }
}
